# https://docs.travis-ci.com/user/languages/python/#python-37-and-higher
dist: xenial
language: python
sudo: false
matrix:
  include:
    - python: "3.5"
      env: TOX_ENV=py35
    - python: "3.6"
      env: TOX_ENV=py36
    - python: "3.7"
      env: TOX_ENV=py37
    - python: "pypy3.5"
      env: TOX_ENV=pypy3
    - python: "3.6"
      env: TOX_ENV=analysis
    - python: "3.6"
      env: TOX_ENV=coverage
install:
 - pip install tox
 - pip install coveralls
script:
 - tox -e $TOX_ENV
after_success:
 - if [[ $TOX_ENV = "coverage" ]]; then coveralls; fi
